create table if not exists account
(
    id            uuid         not null primary key,
    provider      varchar(20)  null, -- GOOGLE
    email         varchar(255) not null unique,
    name          varchar(50)  not null unique,
    password      varchar(255) null, -- 소셜 유저는 x
    refresh_token varchar(300) null,

    created_at    timestamp    not null default now(),
    updated_at    timestamp    not null default now(),
    archived_at   timestamp    null
);

CREATE INDEX IF NOT EXISTS idx_account_email ON account (email);

CREATE TABLE IF NOT EXISTS default_nickname
(
    id              bigint       not null generated by default as identity primary key,
    name            varchar(10)  not null unique,
    num             int          not null, -- 0 ~ 999

    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now(),
    archived_at     TIMESTAMP
);