create table if not exists debate
(
    id             uuid         not null primary key,
    host_id        uuid         not null,
    book_id        bigint       not null,
    topic          varchar(100) not null,
    description    varchar(300) null,
    closed_at      timestamp    null,

    created_at     timestamp    not null,
    updated_at     timestamp    not null,
    archived_at    timestamp    null
);

create table if not exists debate_member
(
    id          bigint      not null generated by default as identity primary key,
    debate_id   uuid        not null,
    account_id  uuid        not null,
    role        varchar(10) not null, -- HOST, MEMBER

    created_at  timestamp   not null,
    updated_at  timestamp   not null,
    archived_at timestamp   null
);

create table if not exists debate_round
(
    id              bigint      not null generated by default as identity primary key,
    debate_id       uuid        not null,
    type            varchar(20) not null, -- PRESENTATION, FREE
    next_speaker_id uuid        null,
    ended_at        timestamp   null,

    created_at      timestamp   not null,
    updated_at      timestamp   not null,
    archived_at     timestamp   null
);

create table if not exists debate_round_speaker
(
    id              bigint    not null generated by default as identity primary key,
    debate_round_id bigint    not null,
    account_id      uuid      not null,
    is_active       boolean   not null,
    ended_at        timestamp not null,

    created_at      timestamp not null,
    updated_at      timestamp not null,
    archived_at     timestamp null
);

create table if not exists debate_chat
(
    id          bigint    not null generated by default as identity primary key,
    debate_id   uuid      not null,
    account_id  uuid      not null,
    content     text      not null,

    created_at  timestamp not null default now(),
    updated_at  timestamp not null default now(),
    archived_at timestamp null
);

create table if not exists debate_summarization
(
    id          bigint    not null generated by default as identity primary key,
    debate_id   uuid      not null,
    content     text      not null,

    created_at  timestamp not null default now(),
    updated_at  timestamp not null default now(),
    archived_at timestamp null
);