create table if not exists book
(
    id          bigint        not null generated by default as identity primary key,
    isbn        varchar(20)   not null unique,
    author      varchar(50)   not null,
    title       varchar(50)   not null,
    description varchar(5000) null,
    image_url   varchar(300)  null,

    created_at  timestamp     not null,
    updated_at  timestamp     not null,
    archived_at timestamp     null
);

create index if not exists idx_book_isbn on book (isbn);
