create table if not exists survey
(
    id          bigint        not null generated by default as identity primary key,
    account_id  uuid          not null,
    rate        int           not null, -- [0 ~ 10]

    created_at  timestamp     not null default now(),
    updated_at  timestamp     not null default now(),
    archived_at timestamp     null
);
