-- TODO: FK 제약조건 삭제하기. 비즈니스 로직에서 해결 가능

CREATE TABLE IF NOT EXISTS ai_chat
(
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    debate_id       UUID         NOT NULL,
    persona_id      VARCHAR(2)  NOT NULL,
    name            VARCHAR(100) NOT NULL,

    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now(),
    archived_at     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_debate_id ON ai_chat (debate_id);

CREATE TABLE IF NOT EXISTS ai_chat_persona
(
    id          VARCHAR(2)   PRIMARY KEY, -- a, b ...
    agent_id    VARCHAR(100) NOT NULL,

    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now(),
    archived_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_chat_message
(
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chat_id     UUID         NOT NULL REFERENCES ai_chat (id),
    role        VARCHAR(20)  NOT NULL,
    content     TEXT         NOT NULL,
    status      VARCHAR(20)  NOT NULL, -- PENDING, COMPLETED, FAILED

    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now(),
    archived_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_message_chat_id ON ai_chat_message (chat_id);

CREATE TABLE IF NOT EXISTS ai_chat_member
(
    id          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     UUID         NOT NULL REFERENCES ai_chat (id),
    account_id  UUID         NOT NULL REFERENCES account (id),

    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now(),
    archived_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_member_chat_id ON ai_chat_member (chat_id);
CREATE INDEX IF NOT EXISTS idx_ai_chat_member_account_id ON ai_chat_member (account_id);

CREATE TABLE IF NOT EXISTS ai_chat_search_result
(
    id          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     UUID         NOT NULL REFERENCES ai_chat (id),
    type        VARCHAR(10)  NOT NULL, -- NEWS, BLOG
    title       TEXT         NOT NULL,
    url         TEXT         NOT NULL,
    content     TEXT         NOT NULL,

    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now(),
    archived_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_search_result_chat_id ON ai_chat_search_result (chat_id);