CREATE TABLE IF NOT EXISTS default_nickname
(
    id              bigint       not null generated by default as identity primary key,
    name            varchar(10)  not null unique,
    num             int          not null, -- 0 ~ 999

    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now(),
    archived_at     TIMESTAMP
);