language: "ko-KR"
early_access: false
tone_instructions: "μΉμ ν•μ§€λ§ μ‹ μ¤‘ν•κ³  ν•µμ‹¬λ§ λ…ν™•ν•κ² μ„¤λ…ν•΄μ£Όμ„Έμ”. μ½”λ“ κ°μ„  λ° μ μ•μ€ κµ¬μ²΄μ μΈ μμ‹ μ½”λ“λ¥Ό ν¬ν•¨ν•΄μ£Όμ„Έμ”."

reviews:
  high_level_summary: true
  review_status: true
  poem: false
  collapse_walkthrough: true
  sequence_diagrams: true

  # path λ³„ λ¦¬λ·° μ§€μ‹μ‚¬ν•­
  path_instructions:
    # μ „μ²΄ Kotlin μ½”λ“ λ¦¬λ·°
    - path: "**/*.kt"
      instructions: |
        "μ „μ²΄ μ½”ν‹€λ¦° μ½”λ“μ— λ€ν•΄ λ‹¤μ κΈ°μ¤€μ— λ”°λΌ λ¦¬λ·°ν•΄μ£Όμ„Έμ”!

        π“ μ½”λ“ ν’μ§:
        - λ΅μ§ μ¤λ¥λ‚ μμ™Έ μƒν™©μ€ μ—†λ”μ§€μ”?
        - μ„±λ¥μ„ κ°μ„ ν•  μ μλ” μ—¬μ§€κ°€ μμ„κΉμ”?
        - λ³΄μ•μ μΌλ΅ λ―Όκ°ν• λ΅μ§μ€ μ•μ „ν•κ² μ‘μ„±λμ—λ”μ§€ ν™•μΈν•΄μ£Όμ„Έμ”!
        - ν™•μ¥μ„± μΈ΅λ©΄μ—μ„ ν–¥ν›„ κΈ°λ¥ μ¶”κ°€κ°€ μ μ—°ν•κ² κ°€λ¥ν• μ§€ λ΄μ£Όμ„Έμ”.

        π”§ μ μ§€λ³΄μμ„±:
        - μ½”λ“ λ³µμ΅λ„λ” μ μ ν•κ°€μ”? λ„λ¬΄ λ§μ€ μ±…μ„μ„ κ°€μ§„ ν•¨μλ” μ—†λ‚μ”?
        - ν…μ¤νΈν•κΈ° μ‰¬μ΄ κµ¬μ΅°μΈκ°€μ”? (μμ΅΄μ„± λ¶„λ¦¬ λ“±)
        - λ¬Έμ„ν™”λ‚ μ£Όμ„μ΄ ν•„μ”ν• λ¶€λ¶„μ€ μλ‚μ”?
        - κΈ°μ μ  λ¶€μ±„λ΅ μ΄μ–΄μ§ μ μλ” μ„μ‹ μ½”λ“λ‚ ν•λ“μ½”λ”©μ€ μ—†λ”μ§€ ν™•μΈν•΄μ£Όμ„Έμ”!

        λν• μ½”ν‹€λ¦° κ΄€μ©κµ¬, null μ²λ¦¬, λ¶λ³€μ„±(val μ‚¬μ©), ν™•μ¥ ν•¨μ ν™μ© λ“± μ½”ν‹€λ¦°λ‹µκ² μ‘μ„±λμ—λ”μ§€λ„ ν•¨κ» κ²€ν† ν•΄μ£Όμ„Έμ”."

    # Data λ¨λ“ - Entity & Repository
    - path: "**/data/src/main/kotlin/kr/co/booktalk/domain/**/*.kt"
      instructions: |
        "μ—”ν‹°ν‹°λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - @Entity, @Table μ„¤μ •μ΄ μ μ ν•κ°€μ”?
        - μ—°κ΄€κ΄€κ³„ λ§¤ν•‘(@ManyToOne, @OneToMany λ“±)μ΄ μ λμ–΄μλ‚μ”?
        - FetchType μ„¤μ •μ΄ μ μ ν•κ°€μ”? (LAZY vs EAGER)
        - AuditableUuidEntity μƒμ†μ΄ μ μ ν ν™μ©λκ³  μλ‚μ”?
        - λ¶λ³€μ„±μ„ μ μ§€ν‚¤κ³  μλ‚μ”? (val μ‚¬μ©)

        λ¦¬ν¬μ§€ν† λ¦¬λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - μΏΌλ¦¬ λ©”μ†λ“ λ„¤μ΄λ°μ΄ λ…ν™•ν•κ°€μ”?
        - @Transactional(readOnly = true) μ„¤μ •μ΄ μ μ ν•κ°€μ”?
        - N+1 λ¬Έμ λ” μ—†λ‚μ”?
        - νμ΄μ§•/μ •λ ¬μ΄ ν•„μ”ν• κ²½μ° μ μ ν κµ¬ν„λμ–΄ μλ‚μ”?
        - Spring Data JPAμ κΈ°λ¥μ„ μ ν™μ©ν•κ³  μλ‚μ”?"

    # API λ¨λ“ - Service
    - path: "**/api/src/main/kotlin/kr/co/booktalk/domain/**/*Service.kt"
      instructions: |
        "μ„λΉ„μ¤λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - λΉ„μ¦λ‹μ¤ λ΅μ§μ μ±…μ„μ΄ λ…ν™•ν•κ³  λ„λ©”μΈ μ¤‘μ‹¬μ μΈκ°€μ”?
        - @Service μ–΄λ…Έν…μ΄μ…μ΄ μ μ ν μ‚¬μ©λμ—λ‚μ”?
        - @Transactional μ‚¬μ©μ΄ μ μ ν•κ°€μ”? (μ½κΈ° μ „μ© νΈλμ­μ… κµ¬λ¶„)
        - μμ™Έ μ²λ¦¬κ°€ μΌκ΄€λκ² μ²λ¦¬λκ³  μλ‚μ”?
        - μμ΅΄μ„± μ£Όμ…μ΄ μƒμ„±μ κΈ°λ°μΌλ΅ μ΄λ¤„μ§€κ³  μλ‚μ”?
        - λ‹¤λ¥Έ μ„λΉ„μ¤μ™€μ ν‘λ ¥μ΄ λ…ν™•ν•κ°€μ”?
        - λ„λ©”μΈ λ΅μ§κ³Ό μΈν”„λΌ λ΅μ§μ΄ μ μ ν λ¶„λ¦¬λμ–΄ μλ‚μ”?"

    # API λ¨λ“ - Controller
    - path: "**/api/src/main/kotlin/kr/co/booktalk/domain/**/*Controller.kt"
      instructions: |
        "μ»¨νΈλ΅¤λ¬λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - @RestControllerμ™€ @RequestMapping μ„¤μ •μ΄ μ μ ν•κ°€μ”?
        - REST APIμ URI, HTTP λ©”μ„λ“ μ„¤κ³„κ°€ RESTfulν•κ°€μ”?
        - μ”μ²­(@RequestBody) λ° μ‘λ‹µ DTOκ°€ λ…ν™•ν•κ² μ •μλμ–΄ μλ‚μ”?
        - @Validλ¥Ό ν†µν• μ”μ²­ κ²€μ¦μ΄ μ μ ν μ΄λ£¨μ–΄μ§€κ³  μλ‚μ”?
        - JWT μΈμ¦μ΄ ν•„μ”ν• μ—”λ“ν¬μΈνΈμ— @JwtAuthκ°€ μ μ ν μ μ©λμ–΄ μλ‚μ”?
        - μμ™Έ λ°μƒ μ‹ μ μ ν• μ—λ¬ μ‘λ‹µμ„ λ¦¬ν„΄ν•κ³  μλ‚μ”?
        - API λ¬Έμ„ν™”λ¥Ό μ„ν• μ •λ³΄κ°€ μ¶©λ¶„ν•κ°€μ”?"

    # API λ¨λ“ - Request/Response DTOs & Validators
    - path: "**/api/src/main/kotlin/kr/co/booktalk/domain/**/_*.kt"
      instructions: |
        "DTO λ° Validator νμΌμ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - Request/Response DTOκ°€ λ…ν™•ν•κ² λ¶„λ¦¬λμ–΄ μλ‚μ”?
        - data classλ¥Ό ν™μ©ν•μ—¬ λ¶λ³€μ„±μ΄ λ³΄μ¥λλ‚μ”?
        - Validator λ΅μ§μ΄ μ μ ν•κ°€μ”?
        - λΉ„μ¦λ‹μ¤ κ·μΉ™μ΄ λ…ν™•ν•κ² κ²€μ¦λκ³  μλ‚μ”?
        - μ—λ¬ λ©”μ‹μ§€κ°€ μ‚¬μ©μ μΉν™”μ μΈκ°€μ”?"

    # Config μ„¤μ • νμΌλ“¤
    - path: "**/src/main/kotlin/kr/co/booktalk/config/**/*.kt"
      instructions: |
        "μ„¤μ • ν΄λμ¤λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - @Configuration, @EnableJpaAuditing λ“± μ„¤μ • μ–΄λ…Έν…μ΄μ…μ΄ μ μ ν•κ°€μ”?
        - μ„¤μ • κ°’λ“¤μ΄ ν™κ²½λ³€μλ‚ application.yamlμ—μ„ μ™Έλ¶€ν™”λμ–΄ μλ‚μ”?
        - λ³΄μ• κ΄€λ ¨ μ„¤μ •(JWT, CORS λ“±)μ΄ μ•μ „ν•κ² κµ¬μ„±λμ–΄ μλ‚μ”?
        - Bean μ„¤μ •μ΄ λ…ν™•ν•κ³  μν™ μ°Έμ΅°κ°€ μ—†λ‚μ”?
        - DataSource, JPA μ„¤μ •μ΄ ν”„λ΅λ•μ…μ— μ ν•©ν•κ°€μ”?"

    # Lib λ¨λ“ - κ³µν†µ μ ν‹Έλ¦¬ν‹°
    - path: "**/lib/src/main/kotlin/kr/co/booktalk/**/*.kt"
      instructions: |
        "λΌμ΄λΈλ¬λ¦¬ λ¨λ“μ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - κ³µν†µ κΈ°λ¥μ΄ μ μ¶”μƒν™”λμ–΄ μλ‚μ”?
        - λ‹¤λ¥Έ λ¨λ“μ—μ„ μ¬μ‚¬μ©ν•κΈ° μ‰¬μ΄ κµ¬μ΅°μΈκ°€μ”?
        - μ™Έλ¶€ μμ΅΄μ„±μ΄ μµμ†ν™”λμ–΄ μλ‚μ”?
        - JWT μ²λ¦¬(JwtService)κ°€ μ•μ „ν•κ² κµ¬ν„λμ–΄ μλ‚μ”?
        - μ•”νΈν™”(Crypto, BCrypt) λ΅μ§μ΄ λ³΄μ• λ¨λ²” μ‚¬λ΅€λ¥Ό λ”°λ¥΄λ‚μ”?
        - HTTP Client(BookClient) μ„¤μ •μ΄ μ μ ν•κ°€μ”? (timeout, retry λ“±)
        - μ—λ¬ μ²λ¦¬κ°€ μΌκ΄€λκ² λμ–΄ μλ‚μ”?"

    # ν…μ¤νΈ μ½”λ“
    - path: "**/src/test/kotlin/**/*Test.kt"
      instructions: |
        "ν…μ¤νΈ μ½”λ“λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - @SpringBootTest, @DataJpaTest λ“± ν…μ¤νΈ μ–΄λ…Έν…μ΄μ…μ΄ μ μ ν•κ°€μ”?
        - ν…μ¤νΈ κ²©λ¦¬κ°€ μ λμ–΄μλ‚μ”? (@Transactional, @DirtiesContext)
        - λ¨ν‚Ήμ΄ ν•„μ”ν• κ²½μ° MockKλ‚ Mockitoκ°€ μ μ ν μ‚¬μ©λμ—λ‚μ”?
        - Given-When-Then ν¨ν„΄μ΄λ‚ λ…ν™•ν• ν…μ¤νΈ κµ¬μ΅°λ¥Ό λ”°λ¥΄λ‚μ”?
        - μ—£μ§€ μΌ€μ΄μ¤μ™€ μμ™Έ μƒν™©μ„ ν…μ¤νΈν•λ‚μ”?
        - ν…μ¤νΈ λ°μ΄ν„° μ„¤μ •μ΄ λ…ν™•ν•κ°€μ”?
        - ν†µν•© ν…μ¤νΈμ™€ λ‹¨μ„ ν…μ¤νΈκ°€ μ μ ν λ¶„λ¦¬λμ–΄ μλ‚μ”?"

    # μ„¤μ • νμΌ
    - path: "**/src/main/resources/application*.yaml"
      instructions: |
        "μ„¤μ • νμΌμ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - ν”„λ΅νμΌ λ¶„λ¦¬κ°€ μ λμ–΄μλ‚μ”? (local, dev, prod λ“±)
        - λ―Όκ° μ •λ³΄κ°€ ν•λ“μ½”λ”©λμ–΄ μμ§€ μ•λ‚μ”?
        - JPA μ„¤μ •(show-sql, ddl-auto λ“±)μ΄ ν™κ²½λ³„λ΅ μ μ ν•κ°€μ”?
        - DB μ—°κ²° μ„¤μ •μ΄ λ…ν™•ν•κ² μ •μλμ–΄ μλ‚μ”?
        - λ΅κΉ… λ λ²¨μ΄ ν™κ²½λ³„λ΅ μ μ ν•κ°€μ”?
        - JWT μ„¤μ •μ΄ μ•μ „ν•κ² κµ¬μ„±λμ–΄ μλ‚μ”?"

    # ν™κ²½ λ³€μ νμΌ
    - path: "**/.env*"
      instructions: |
        "ν™κ²½ λ³€μ νμΌμ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - λ―Όκ°ν• μ •λ³΄(λΉ„λ°€λ²νΈ, μ‹ν¬λ¦Ώ ν‚¤)κ°€ μ•μ „ν•κ² κ΄€λ¦¬λλ‚μ”?
        - .gitignoreμ— ν¬ν•¨λμ–΄ μλ‚μ”?
        - μμ  νμΌ(.env.example)μ΄ μ κ³µλλ‚μ”?
        - λ³€μλ…μ΄ λ…ν™•ν•κ³  μΌκ΄€μ„± μλ‚μ”?"

    # SQL μ¤ν‚¤λ§ νμΌ
    - path: "**/resources/schema/**/*.sql"
      instructions: |
        "SQL μ¤ν‚¤λ§λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - ν…μ΄λΈ” κµ¬μ΅°κ°€ μ—”ν‹°ν‹°μ™€ μΌμΉν•λ‚μ”?
        - μΈλ±μ¤κ°€ μ μ ν μ„¤μ •λμ–΄ μλ‚μ”?
        - μ™Έλν‚¤ μ μ•½μ΅°κ±΄μ΄ μ¬λ°”λ¥΄κ² μ„¤μ •λμ–΄ μλ‚μ”?
        - λ„¤μ΄λ° μ»¨λ²¤μ…μ΄ μΌκ΄€λλ‚μ”? (snake_case)
        - NOT NULL, UNIQUE μ μ•½μ΄ λΉ„μ¦λ‹μ¤ κ·μΉ™κ³Ό μΌμΉν•λ‚μ”?"

    # Gradle λΉλ“ νμΌ
    - path: "**/build.gradle.kts"
      instructions: |
        "Gradle μ„¤μ •μ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - μμ΅΄μ„± λ²„μ „μ΄ μµμ‹ μ΄λ©΄μ„ μ•μ •μ μΈκ°€μ”?
        - λ¶ν•„μ”ν• μμ΅΄μ„±μ€ μ—†λ‚μ”?
        - λ¨λ“ κ°„ μμ΅΄μ„±μ΄ λ…ν™•ν•κ°€μ”?
        - ν”λ¬κ·ΈμΈ μ„¤μ •μ΄ μ μ ν•κ°€μ”?"

  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "μ‘μ—…μ¤‘"
      - "Draft"
    drafts: false
    base_branches:
      - "main"
      - "develop"
      - "dev"

chat:
  auto_reply: true