language: "ko-KR"
early_access: false
tone_instructions: "μΉμ ν•μ§€λ§ μ‹ μ¤‘ν•κ³  ν•µμ‹¬λ§ λ…ν™•ν•κ² μ„¤λ…ν•΄μ£Όμ„Έμ”. μ½”λ“ κ°μ„  λ° μ μ•μ€ κµ¬μ²΄μ μΈ μμ‹ μ½”λ“λ¥Ό ν¬ν•¨ν•΄μ£Όμ„Έμ”."

reviews:
  high_level_summary: true
  review_status: true
  poem: false
  collapse_walkthrough: true
  sequence_diagrams: true

  # path λ³„ λ¦¬λ·° μ§€μ‹μ‚¬ν•­
  path_instructions:
    # ============ Backend (Kotlin/Spring Boot) ============

    # μ „μ²΄ Kotlin μ½”λ“ λ¦¬λ·°
    - path: "book-talk-be/**/*.kt"
      instructions: |
        "μ „μ²΄ μ½”ν‹€λ¦° μ½”λ“μ— λ€ν•΄ λ‹¤μ κΈ°μ¤€μ— λ”°λΌ λ¦¬λ·°ν•΄μ£Όμ„Έμ”!

        π“ μ½”λ“ ν’μ§:
        - λ΅μ§ μ¤λ¥λ‚ μμ™Έ μƒν™©μ€ μ—†λ”μ§€μ”?
        - μ„±λ¥μ„ κ°μ„ ν•  μ μλ” μ—¬μ§€κ°€ μμ„κΉμ”?
        - λ³΄μ•μ μΌλ΅ λ―Όκ°ν• λ΅μ§μ€ μ•μ „ν•κ² μ‘μ„±λμ—λ”μ§€ ν™•μΈν•΄μ£Όμ„Έμ”!
        - ν™•μ¥μ„± μΈ΅λ©΄μ—μ„ ν–¥ν›„ κΈ°λ¥ μ¶”κ°€κ°€ μ μ—°ν•κ² κ°€λ¥ν• μ§€ λ΄μ£Όμ„Έμ”.

        π”§ μ μ§€λ³΄μμ„±:
        - μ½”λ“ λ³µμ΅λ„λ” μ μ ν•κ°€μ”? λ„λ¬΄ λ§μ€ μ±…μ„μ„ κ°€μ§„ ν•¨μλ” μ—†λ‚μ”?
        - ν…μ¤νΈν•κΈ° μ‰¬μ΄ κµ¬μ΅°μΈκ°€μ”? (μμ΅΄μ„± λ¶„λ¦¬ λ“±)
        - λ¬Έμ„ν™”λ‚ μ£Όμ„μ΄ ν•„μ”ν• λ¶€λ¶„μ€ μλ‚μ”?
        - κΈ°μ μ  λ¶€μ±„λ΅ μ΄μ–΄μ§ μ μλ” μ„μ‹ μ½”λ“λ‚ ν•λ“μ½”λ”©μ€ μ—†λ”μ§€ ν™•μΈν•΄μ£Όμ„Έμ”!

        λν• μ½”ν‹€λ¦° κ΄€μ©κµ¬, null μ²λ¦¬, λ¶λ³€μ„±(val μ‚¬μ©), ν™•μ¥ ν•¨μ ν™μ© λ“± μ½”ν‹€λ¦°λ‹µκ² μ‘μ„±λμ—λ”μ§€λ„ ν•¨κ» κ²€ν† ν•΄μ£Όμ„Έμ”."

    # Data λ¨λ“ - Entity & Repository
    - path: "book-talk-be/_data/src/main/kotlin/kr/co/booktalk/domain/**/*.kt"
      instructions: |
        "μ—”ν‹°ν‹°λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - @Entity, @Table μ„¤μ •μ΄ μ μ ν•κ°€μ”?
        - μ—°κ΄€κ΄€κ³„ λ§¤ν•‘(@ManyToOne, @OneToMany λ“±)μ΄ μ λμ–΄μλ‚μ”?
        - FetchType μ„¤μ •μ΄ μ μ ν•κ°€μ”? (LAZY vs EAGER)
        - AuditableUuidEntity μƒμ†μ΄ μ μ ν ν™μ©λκ³  μλ‚μ”?
        - λ¶λ³€μ„±μ„ μ μ§€ν‚¤κ³  μλ‚μ”? (val μ‚¬μ©)

        λ¦¬ν¬μ§€ν† λ¦¬λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - μΏΌλ¦¬ λ©”μ†λ“ λ„¤μ΄λ°μ΄ λ…ν™•ν•κ°€μ”?
        - @Transactional(readOnly = true) μ„¤μ •μ΄ μ μ ν•κ°€μ”?
        - N+1 λ¬Έμ λ” μ—†λ‚μ”?
        - νμ΄μ§•/μ •λ ¬μ΄ ν•„μ”ν• κ²½μ° μ μ ν κµ¬ν„λμ–΄ μλ‚μ”?
        - Spring Data JPAμ κΈ°λ¥μ„ μ ν™μ©ν•κ³  μλ‚μ”?"

    # API λ¨λ“ - Service
    - path: "book-talk-be/_api/src/main/kotlin/kr/co/booktalk/domain/**/*Service.kt"
      instructions: |
        "μ„λΉ„μ¤λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - λΉ„μ¦λ‹μ¤ λ΅μ§μ μ±…μ„μ΄ λ…ν™•ν•κ³  λ„λ©”μΈ μ¤‘μ‹¬μ μΈκ°€μ”?
        - @Service μ–΄λ…Έν…μ΄μ…μ΄ μ μ ν μ‚¬μ©λμ—λ‚μ”?
        - @Transactional μ‚¬μ©μ΄ μ μ ν•κ°€μ”? (μ½κΈ° μ „μ© νΈλμ­μ… κµ¬λ¶„)
        - μμ™Έ μ²λ¦¬κ°€ μΌκ΄€λκ² μ²λ¦¬λκ³  μλ‚μ”?
        - μμ΅΄μ„± μ£Όμ…μ΄ μƒμ„±μ κΈ°λ°μΌλ΅ μ΄λ¤„μ§€κ³  μλ‚μ”?
        - λ‹¤λ¥Έ μ„λΉ„μ¤μ™€μ ν‘λ ¥μ΄ λ…ν™•ν•κ°€μ”?
        - λ„λ©”μΈ λ΅μ§κ³Ό μΈν”„λΌ λ΅μ§μ΄ μ μ ν λ¶„λ¦¬λμ–΄ μλ‚μ”?"

    # API λ¨λ“ - Controller
    - path: "book-talk-be/_api/src/main/kotlin/kr/co/booktalk/domain/**/*Controller.kt"
      instructions: |
        "μ»¨νΈλ΅¤λ¬λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - @RestControllerμ™€ @RequestMapping μ„¤μ •μ΄ μ μ ν•κ°€μ”?
        - REST APIμ URI, HTTP λ©”μ„λ“ μ„¤κ³„κ°€ RESTfulν•κ°€μ”?
        - μ”μ²­(@RequestBody) λ° μ‘λ‹µ DTOκ°€ λ…ν™•ν•κ² μ •μλμ–΄ μλ‚μ”?
        - @Validλ¥Ό ν†µν• μ”μ²­ κ²€μ¦μ΄ μ μ ν μ΄λ£¨μ–΄μ§€κ³  μλ‚μ”?
        - JWT μΈμ¦μ΄ ν•„μ”ν• μ—”λ“ν¬μΈνΈμ— @JwtAuthκ°€ μ μ ν μ μ©λμ–΄ μλ‚μ”?
        - μμ™Έ λ°μƒ μ‹ μ μ ν• μ—λ¬ μ‘λ‹µμ„ λ¦¬ν„΄ν•κ³  μλ‚μ”?
        - API λ¬Έμ„ν™”λ¥Ό μ„ν• μ •λ³΄κ°€ μ¶©λ¶„ν•κ°€μ”?"

    # API λ¨λ“ - Request/Response DTOs & Validators
    - path: "book-talk-be/_api/src/main/kotlin/kr/co/booktalk/domain/**/_*.kt"
      instructions: |
        "DTO λ° Validator νμΌμ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - Request/Response DTOκ°€ λ…ν™•ν•κ² λ¶„λ¦¬λμ–΄ μλ‚μ”?
        - data classλ¥Ό ν™μ©ν•μ—¬ λ¶λ³€μ„±μ΄ λ³΄μ¥λλ‚μ”?
        - Validator λ΅μ§μ΄ μ μ ν•κ°€μ”?
        - λΉ„μ¦λ‹μ¤ κ·μΉ™μ΄ λ…ν™•ν•κ² κ²€μ¦λκ³  μλ‚μ”?
        - μ—λ¬ λ©”μ‹μ§€κ°€ μ‚¬μ©μ μΉν™”μ μΈκ°€μ”?"

    # API λ¨λ“ - WebSocket Handler
    - path: "book-talk-be/_api/src/main/kotlin/kr/co/booktalk/domain/webSocket/**/*.kt"
      instructions: |
        "WebSocket ν•Έλ“¤λ¬λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - WebSocket μ—°κ²°/ν•΄μ  μ‹ λ¦¬μ†μ¤ μ •λ¦¬κ°€ μ μ ν•κ°€μ”?
        - λ©”μ‹μ§€ νƒ€μ…λ³„ μ²λ¦¬κ°€ λ…ν™•ν•κ² λ¶„λ¦¬λμ–΄ μλ‚μ”?
        - μΈμ¦ κ²€μ¦μ΄ μ¬λ°”λ¥΄κ² μ΄λ£¨μ–΄μ§€λ‚μ”? (accountId λ§¤μΉ­)
        - λΈλ΅λ“μΊμ¤νΈ λ΅μ§μ΄ thread-safeν•κ°€μ”?
        - μ„Έμ… κ΄€λ¦¬κ°€ μ•μ „ν•κ°€μ”? (ConcurrentHashMap μ‚¬μ©)
        - WebRTC signaling λ©”μ‹μ§€κ°€ μ¬λ°”λ¥΄κ² μ¤‘κ³„λλ‚μ”?
        - μ—λ¬ μ²λ¦¬κ°€ μ μ ν•κ°€μ”? (μ—°κ²° λκΉ€, λ©”μ‹μ§€ νμ‹± μ‹¤ν¨ λ“±)
        - λ΅κ·Έκ°€ μ¶©λ¶„ν•κ³  λ…ν™•ν•κ°€μ”?"

    # Config μ„¤μ • νμΌλ“¤
    - path: "book-talk-be/_api/src/main/kotlin/kr/co/booktalk/config/**/*.kt"
      instructions: |
        "μ„¤μ • ν΄λμ¤λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - @Configuration, @EnableJpaAuditing λ“± μ„¤μ • μ–΄λ…Έν…μ΄μ…μ΄ μ μ ν•κ°€μ”?
        - μ„¤μ • κ°’λ“¤μ΄ ν™κ²½λ³€μλ‚ application.yamlμ—μ„ μ™Έλ¶€ν™”λμ–΄ μλ‚μ”?
        - λ³΄μ• κ΄€λ ¨ μ„¤μ •(JWT, CORS λ“±)μ΄ μ•μ „ν•κ² κµ¬μ„±λμ–΄ μλ‚μ”?
        - Bean μ„¤μ •μ΄ λ…ν™•ν•κ³  μν™ μ°Έμ΅°κ°€ μ—†λ‚μ”?
        - DataSource, JPA μ„¤μ •μ΄ ν”„λ΅λ•μ…μ— μ ν•©ν•κ°€μ”?"

    # Lib λ¨λ“ - κ³µν†µ μ ν‹Έλ¦¬ν‹°
    - path: "book-talk-be/_lib/src/main/kotlin/kr/co/booktalk/**/*.kt"
      instructions: |
        "λΌμ΄λΈλ¬λ¦¬ λ¨λ“μ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - κ³µν†µ κΈ°λ¥μ΄ μ μ¶”μƒν™”λμ–΄ μλ‚μ”?
        - λ‹¤λ¥Έ λ¨λ“μ—μ„ μ¬μ‚¬μ©ν•κΈ° μ‰¬μ΄ κµ¬μ΅°μΈκ°€μ”?
        - μ™Έλ¶€ μμ΅΄μ„±μ΄ μµμ†ν™”λμ–΄ μλ‚μ”?
        - JWT μ²λ¦¬(JwtService)κ°€ μ•μ „ν•κ² κµ¬ν„λμ–΄ μλ‚μ”?
        - μ•”νΈν™”(Crypto, BCrypt) λ΅μ§μ΄ λ³΄μ• λ¨λ²” μ‚¬λ΅€λ¥Ό λ”°λ¥΄λ‚μ”?
        - HTTP Client(BookClient) μ„¤μ •μ΄ μ μ ν•κ°€μ”? (timeout, retry λ“±)
        - μ—λ¬ μ²λ¦¬κ°€ μΌκ΄€λκ² λμ–΄ μλ‚μ”?"

    # ν…μ¤νΈ μ½”λ“
    - path: "book-talk-be/**/src/test/kotlin/**/*Test.kt"
      instructions: |
        "ν…μ¤νΈ μ½”λ“λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - @SpringBootTest, @DataJpaTest λ“± ν…μ¤νΈ μ–΄λ…Έν…μ΄μ…μ΄ μ μ ν•κ°€μ”?
        - ν…μ¤νΈ κ²©λ¦¬κ°€ μ λμ–΄μλ‚μ”? (@Transactional, @DirtiesContext)
        - λ¨ν‚Ήμ΄ ν•„μ”ν• κ²½μ° MockKλ‚ Mockitoκ°€ μ μ ν μ‚¬μ©λμ—λ‚μ”?
        - Given-When-Then ν¨ν„΄μ΄λ‚ λ…ν™•ν• ν…μ¤νΈ κµ¬μ΅°λ¥Ό λ”°λ¥΄λ‚μ”?
        - μ—£μ§€ μΌ€μ΄μ¤μ™€ μμ™Έ μƒν™©μ„ ν…μ¤νΈν•λ‚μ”?
        - ν…μ¤νΈ λ°μ΄ν„° μ„¤μ •μ΄ λ…ν™•ν•κ°€μ”?
        - ν†µν•© ν…μ¤νΈμ™€ λ‹¨μ„ ν…μ¤νΈκ°€ μ μ ν λ¶„λ¦¬λμ–΄ μλ‚μ”?"

    # μ„¤μ • νμΌ
    - path: "book-talk-be/_api/src/main/resources/application*.yaml"
      instructions: |
        "μ„¤μ • νμΌμ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - ν”„λ΅νμΌ λ¶„λ¦¬κ°€ μ λμ–΄μλ‚μ”? (local, dev, prod λ“±)
        - λ―Όκ° μ •λ³΄κ°€ ν•λ“μ½”λ”©λμ–΄ μμ§€ μ•λ‚μ”?
        - JPA μ„¤μ •(show-sql, ddl-auto λ“±)μ΄ ν™κ²½λ³„λ΅ μ μ ν•κ°€μ”?
        - DB μ—°κ²° μ„¤μ •μ΄ λ…ν™•ν•κ² μ •μλμ–΄ μλ‚μ”?
        - λ΅κΉ… λ λ²¨μ΄ ν™κ²½λ³„λ΅ μ μ ν•κ°€μ”?
        - JWT μ„¤μ •μ΄ μ•μ „ν•κ² κµ¬μ„±λμ–΄ μλ‚μ”?"

    # SQL μ¤ν‚¤λ§ νμΌ
    - path: "book-talk-be/_data/src/main/resources/schema/**/*.sql"
      instructions: |
        "SQL μ¤ν‚¤λ§λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - ν…μ΄λΈ” κµ¬μ΅°κ°€ μ—”ν‹°ν‹°μ™€ μΌμΉν•λ‚μ”?
        - μΈλ±μ¤κ°€ μ μ ν μ„¤μ •λμ–΄ μλ‚μ”?
        - μ™Έλν‚¤ μ μ•½μ΅°κ±΄μ΄ μ¬λ°”λ¥΄κ² μ„¤μ •λμ–΄ μλ‚μ”?
        - λ„¤μ΄λ° μ»¨λ²¤μ…μ΄ μΌκ΄€λλ‚μ”? (snake_case)
        - NOT NULL, UNIQUE μ μ•½μ΄ λΉ„μ¦λ‹μ¤ κ·μΉ™κ³Ό μΌμΉν•λ‚μ”?"

    # Gradle λΉλ“ νμΌ
    - path: "book-talk-be/**/build.gradle.kts"
      instructions: |
        "Gradle μ„¤μ •μ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - μμ΅΄μ„± λ²„μ „μ΄ μµμ‹ μ΄λ©΄μ„ μ•μ •μ μΈκ°€μ”?
        - λ¶ν•„μ”ν• μμ΅΄μ„±μ€ μ—†λ‚μ”?
        - λ¨λ“ κ°„ μμ΅΄μ„±μ΄ λ…ν™•ν•κ°€μ”?
        - ν”λ¬κ·ΈμΈ μ„¤μ •μ΄ μ μ ν•κ°€μ”?"

    # ============ Frontend (React/TypeScript) ============

    # μ „μ²΄ TypeScript/TSX μ½”λ“ λ¦¬λ·°
    - path: "book-talk-ts/**/*.{ts,tsx}"
      instructions: |
        "TypeScript μ½”λ“μ— λ€ν•΄ λ‹¤μ κΈ°μ¤€μ— λ”°λΌ λ¦¬λ·°ν•΄μ£Όμ„Έμ”!

        π“ μ½”λ“ ν’μ§:
        - νƒ€μ… μ•μ •μ„±μ΄ μ¶©λ¶„ν•κ°€μ”? any μ‚¬μ©μ„ ν”Όν•κ³  μλ‚μ”?
        - λ΅μ§ μ¤λ¥λ‚ μμ™Έ μƒν™©μ€ μ—†λ”μ§€μ”?
        - μ„±λ¥ μµμ ν™” μ—¬μ§€λ” μ—†λ‚μ”? (useMemo, useCallback, React.memo)
        - λ¶ν•„μ”ν• λ¦¬λ λ”λ§μ€ μ—†λ‚μ”?

        π”§ μ μ§€λ³΄μμ„±:
        - μ»΄ν¬λ„νΈ μ±…μ„μ΄ λ…ν™•ν•κ°€μ”? λ„λ¬΄ ν° μ»΄ν¬λ„νΈλ” μ—†λ‚μ”?
        - Custom hooksλ΅ λ΅μ§μ„ μ λ¶„λ¦¬ν–λ‚μ”?
        - μ—λ¬ μ²λ¦¬κ°€ μ μ ν•κ°€μ”?
        - μ½”λ“ μ¤‘λ³µμ€ μ—†λ‚μ”?"

    # React μ»΄ν¬λ„νΈ
    - path: "book-talk-ts/packages/web/src/routes/**/*.tsx"
      instructions: |
        "React μ»΄ν¬λ„νΈλ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - μ»΄ν¬λ„νΈκ°€ λ‹¨μΌ μ±…μ„ μ›μΉ™μ„ λ”°λ¥΄λ‚μ”?
        - Props νƒ€μ…μ΄ λ…ν™•ν•κ² μ •μλμ–΄ μλ‚μ”?
        - useEffectμ μμ΅΄μ„± λ°°μ—΄μ΄ μ¬λ°”λ¥Έκ°€μ”?
        - μ΅°κ±΄λ¶€ λ λ”λ§ λ΅μ§μ΄ λ…ν™•ν•κ°€μ”?
        - μ ‘κ·Όμ„±(a11y)μ„ κ³ λ ¤ν–λ‚μ”?
        - μ—λ¬ λ°”μ΄λ”λ¦¬κ°€ ν•„μ”ν•κ°€μ”?
        - Loading/Error μƒνƒ μ²λ¦¬κ°€ μ μ ν•κ°€μ”?"

    # Custom Hooks
    - path: "book-talk-ts/packages/web/src/hooks/**/*.ts"
      instructions: |
        "Custom Hooksλ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - Hookμ μ±…μ„μ΄ λ…ν™•ν•κ³  μ¬μ‚¬μ© κ°€λ¥ν•κ°€μ”?
        - μμ΅΄μ„± λ°°μ—΄μ΄ μ¬λ°”λ¥΄κ² μ„¤μ •λμ–΄ μλ‚μ”?
        - λ©”λ¨λ¦¬ λ„μ λ°©μ§€λ¥Ό μ„ν• cleanupμ΄ μλ‚μ”?
        - λ°ν™κ°’μ΄ λ…ν™•ν•κ² νƒ€μ… μ •μλμ–΄ μλ‚μ”?
        - Hook λ„¤μ΄λ°μ΄ useλ΅ μ‹μ‘ν•λ‚μ”?
        - μƒνƒ μ—…λ°μ΄νΈκ°€ μ•μ „ν•κ°€μ”? (ν•¨μν• μ—…λ°μ΄νΈ)"

    # Context & Providers
    - path: "book-talk-ts/packages/web/src/contexts/**/*.tsx"
      instructions: |
        "Contextλ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - Contextμ λ²”μ„κ°€ μ μ ν•κ°€μ”? (μ „μ—­ vs μ§€μ—­)
        - Provider μ»΄ν¬λ„νΈκ°€ λ¶ν•„μ”ν• λ¦¬λ λ”λ§μ„ μ λ°ν•μ§€ μ•λ‚μ”?
        - Context valueκ°€ useMemoλ΅ μµμ ν™”λμ–΄ μλ‚μ”?
        - useContext hookμ΄ Provider μ™Έλ¶€μ—μ„ μ‚¬μ©λ  λ• μ—λ¬λ¥Ό λμ§€λ‚μ”?
        - μ΄κΈ°κ°’μ΄ λ…ν™•ν•κ² μ •μλμ–΄ μλ‚μ”?"

    # API ν΄λΌμ΄μ–ΈνΈ
    - path: "book-talk-ts/packages/web/src/apis/**/*.ts"
      instructions: |
        "API ν΄λΌμ΄μ–ΈνΈλ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - HTTP λ©”μ„λ“μ™€ μ—”λ“ν¬μΈνΈκ°€ μ¬λ°”λ¥Έκ°€μ”?
        - μ—λ¬ μ²λ¦¬κ°€ μΌκ΄€λκ² λμ–΄ μλ‚μ”?
        - νƒ€μ… μ •μκ°€ λ°±μ—”λ“ APIμ™€ μΌμΉν•λ‚μ”?
        - μΈμ¦ ν† ν° μ²λ¦¬κ°€ μ•μ „ν•κ°€μ”?
        - μ”μ²­/μ‘λ‹µ νƒ€μ…μ΄ λ…ν™•ν•κ°€μ”?
        - timeout μ„¤μ •μ΄ μ μ ν•κ°€μ”?"

    # WebSocket ν΄λΌμ΄μ–ΈνΈ
    - path: "book-talk-ts/packages/web/src/apis/websocket/**/*.ts"
      instructions: |
        "WebSocket ν΄λΌμ΄μ–ΈνΈλ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - μ—°κ²°/μ¬μ—°κ²° λ΅μ§μ΄ μ•μ „ν•κ°€μ”?
        - λ©”μ‹μ§€ νƒ€μ… κ²€μ¦μ΄ μ μ ν•κ°€μ”? (Zod schema)
        - μ—°κ²° λκΉ€ μ‹ cleanupμ΄ μ¬λ°”λ¥Έκ°€μ”?
        - μ¬μ—°κ²° μ‹ μƒνƒ λ³µκµ¬κ°€ λλ‚μ”?
        - λ©”μ‹μ§€ ν•Έλ“¤λ¬κ°€ λ…ν™•ν•κ² λ¶„λ¦¬λμ–΄ μλ‚μ”?
        - μ—λ¬ μ²λ¦¬κ°€ μ μ ν•κ°€μ”?
        - ν•νΈλΉ„νΈ λ΅μ§μ΄ μλ‚μ”?"

    # WebRTC Manager
    - path: "book-talk-ts/packages/web/src/apis/webrtc/**/*.ts"
      instructions: |
        "WebRTC μ½”λ“λ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - Peer connection μƒμ„±/μΆ…λ£κ°€ μ¬λ°”λ¥Έκ°€μ”?
        - ICE candidate μ²λ¦¬κ°€ μ μ ν•κ°€μ”?
        - Offer/Answer κµν™ λ΅μ§μ΄ μ¬λ°”λ¥Έκ°€μ”?
        - MediaStream κ΄€λ¦¬κ°€ μ•μ „ν•κ°€μ”? (cleanup)
        - μ—°κ²° μƒνƒ λ¨λ‹ν„°λ§μ΄ μλ‚μ”? (connectionState, iceConnectionState)
        - STUN/TURN μ„λ²„ μ„¤μ •μ΄ μ μ ν•κ°€μ”?
        - λ™μ‹ offer μ¶©λ λ°©μ§€(glare prevention)κ°€ λμ–΄ μλ‚μ”?
        - μ¤λ””μ¤ μ„¤μ •μ΄ μ μ ν•κ°€μ”? (echo cancellation, noise suppression)
        - λ¦¬μ†μ¤ λ„μκ°€ μ—†λ‚μ”? (AudioContext cleanup)"

    # TypeScript νƒ€μ… μ •μ
    - path: "book-talk-ts/packages/web/src/types/**/*.ts"
      instructions: |
        "νƒ€μ… μ •μλ” μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - νƒ€μ…μ΄ λ…ν™•ν•κ³  μ¬μ‚¬μ© κ°€λ¥ν•κ°€μ”?
        - anyλ‚ unknown μ‚¬μ©μ΄ μ μ ν•κ°€μ”?
        - μ λ‹μ¨ νƒ€μ…κ³Ό μΈν„°μ„Ήμ… νƒ€μ…μ΄ μ¬λ°”λ¥΄κ² μ‚¬μ©λμ—λ‚μ”?
        - μ λ„¤λ¦­ μ‚¬μ©μ΄ μ μ ν•κ°€μ”?
        - νƒ€μ… κ°€λ“κ°€ ν•„μ”ν•κ°€μ”?"

    # Vite/ν™κ²½ μ„¤μ •
    - path: "book-talk-ts/packages/web/vite.config.ts"
      instructions: |
        "Vite μ„¤μ •μ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - λΉλ“ μµμ ν™” μ„¤μ •μ΄ μ μ ν•κ°€μ”?
        - ν™κ²½ λ³€μ μ²λ¦¬κ°€ μ¬λ°”λ¥Έκ°€μ”?
        - ν”λ¬κ·ΈμΈ μ„¤μ •μ΄ μ μ ν•κ°€μ”?
        - ν”„λ΅μ‹ μ„¤μ •μ΄ ν•„μ”ν•κ°€μ”?
        - Production λΉλ“ μ„¤μ •μ΄ μµμ ν™”λμ–΄ μλ‚μ”?"

    # ν™κ²½ λ³€μ νμΌ
    - path: "**/.env*"
      instructions: |
        "ν™κ²½ λ³€μ νμΌμ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - λ―Όκ°ν• μ •λ³΄(λΉ„λ°€λ²νΈ, μ‹ν¬λ¦Ώ ν‚¤)κ°€ μ•μ „ν•κ² κ΄€λ¦¬λλ‚μ”?
        - .gitignoreμ— ν¬ν•¨λμ–΄ μλ‚μ”?
        - μμ  νμΌ(.env.example)μ΄ μ κ³µλλ‚μ”?
        - λ³€μλ…μ΄ λ…ν™•ν•κ³  μΌκ΄€μ„± μλ‚μ”?
        - ν”„λ΅ νΈμ—”λ“ ν™κ²½λ³€μλ” VITE_ prefixλ¥Ό μ‚¬μ©ν•λ‚μ”?"

    # Package.json
    - path: "book-talk-ts/**/package.json"
      instructions: |
        "package.jsonμ€ μ•„λ μ‚¬ν•­μ„ ν™•μΈν•΄μ£Όμ„Έμ”!
        - μμ΅΄μ„± λ²„μ „μ΄ μ μ ν•κ°€μ”?
        - devDependenciesμ™€ dependenciesκ°€ μ¬λ°”λ¥΄κ² λ¶„λ¦¬λμ–΄ μλ‚μ”?
        - μ¤ν¬λ¦½νΈ λ…λ Ήμ–΄κ°€ λ…ν™•ν•κ°€μ”?
        - λ¶ν•„μ”ν• ν¨ν‚¤μ§€λ” μ—†λ‚μ”?"

  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "μ‘μ—…μ¤‘"
      - "Draft"
    drafts: false
    base_branches:
      - "main"
      - "develop"
      - "dev"

chat:
  auto_reply: true