[versions]
ktor-client = "2.3.12"

[libraries]

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-client" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor-client" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-client" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor-client" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor-client" }

[plugins]

[bundles]
ktor-client = ["ktor-client-cio", "ktor-client-content-negotiation", "ktor-client-core", "ktor-serialization-jackson", "ktor-client-mock"]
